name: Build and Release package
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  
jobs:
  build-release-package:
    name: Build and Release package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: nexus-sonatype
          server-username: NEXUS_USERNAME
          server-password: NEXUS_PASSWORD
          gpg-private-key: ${{ secrets.ICT4H_GPG_KEY }}
      - name: Compare Git tag with Maven version
        run: |
          export GIT_TAG=${GITHUB_REF#refs/tags/}
          PROJECT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [ "$PROJECT_VERSION" != "$GIT_TAG" ]; then
            echo "❌ The Git tag ($GIT_TAG) does not match the Maven version ($PROJECT_VERSION)."
            exit 1
          else
            echo "✅ The Git tag matches the Maven version."
          fi

      - name: Build and deploy with Maven
        run: ./mvnw --no-transfer-progress clean -U deploy -DperformRelease=true
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.ICT4H_GPG_PASSPHRASE }}